### ISSUE TITLE
Make osmium-contrib utilities Windows-compatible

### ISSUE THREAD

**Issue by alex85k** [osmcode/osmium-contrib#2]
I have prepared the CMake script and minimal changes to allow Windows compilation:

To fix compilation with latest Osmium: https://github.com/alex85k/osmium-contrib/commit/a7205d6032ddaa3efca6e44ebe29d6d4300db128
CMake and compatibility: https://github.com/alex85k/osmium-contrib/commit/187acb98aca264e3156f837eee2c02ba855e6ea2

I had to add one OSMIUM_CONSTEXPR and provide dirent & mkdir for MSVC:
(used h-file from http://www.softagalleria.net/dirent.php , the license seems to allow)

Could you check?

**Comment by joto** [comment]
Lots of changes since then. Closing this issue now. Please create new issues if there are remaining issues with building on Windows.
