### ISSUE TITLE
Road length program aborted with error

### ISSUE THREAD

**Issue by yogiks** [osmcode/osmium-contrib#6]
Getting following error when running road_length with an OSM file -
```
terminate called after throwing an instance of 'osmium::not_found'
  what():  location for one or more nodes not found in node location index
Aborted
```
However, other programs like amenity_list worked as expected without any issues. I have set up libosmium and successfully built osmium-contrib without any errors.

**Comment by joto** [comment]
This means that the input file is missing one or more nodes that are needed for some way in the file. You have an incomplete input file, probably an extract that you generated without the `completeWays` option if you used Osmosis or similar.

**Comment by yogiks** [comment]
Yes, issue was with the generated extract. Osmosis with `completeWays=true` option did the trick!
Thanks. :smiley:
