### ISSUE TITLE
Mapolution abort trap error

### ISSUE THREAD

**Issue by chtnha** [osmcode/osmium-contrib#9]
@joto I am trying to use mapolution to create evolution of Bhutan OSM map. I could build libosmium and mapolution without any issues in Mac high sierra (10.13.3). But, when I try to run mapolution with command `./mapolution -S 180 bhutan-internal.osh.pbf`, I am getting abort trap error. 

````
libc++abi.dylib: terminating with uncaught exception of type gdalcpp::gdal_error: failed to create layer 'roads_2007-03-18'
Abort trap: 6

````
![screen shot 2018-07-24 at 12 33 47 am](https://user-images.githubusercontent.com/6770741/43097309-550891a0-8ed9-11e8-837a-b11f336cf870.png)

Please let me know if I missed anything. Thank you!

**Comment by joto** [comment]
The program should create an `out` directory and subdirectories below that. Maybe it can't do that for some reason?

**Comment by chtnha** [comment]
@joto I am able to run mapolution by pulling ubuntu image in iMac using docker. I ran libosmium `ctest` without any GDAL/OGR errors this time. There were two libraries missing in repository. One is `bc` and other is `imagicmagick`. 

Here is the Bhutan output for 10 years (2008-2018)

![bhutan-2008-01-01-2018-04-30](https://user-images.githubusercontent.com/6770741/43643961-9d9abeba-974a-11e8-902f-362877365a9f.gif)
 
Thank you!

**Comment by joto** [comment]
Thanks, I have added the missing dependencies to 7d6d4ef.
